# Change these first
owner: OpenNCCU # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: OpenNCCU App
    url: https://opennccu.com

  - name: OpenNCCU SCSR
    url: https://course.opennccu.com

  - name: OpenNCCU SCSR API
    url: https://course.opennccu.com/api/search
    method: POST
    expectedStatusCodes:
      - 200

  - name: OpenNCCU Oauth
    url: https://oauth.opennccu.com/api/status

  - name: GPA Calculator
    url: https://gpa-calc.opennccu.com/api/gpa
    method: POST
    expectedStatusCodes:
      - 400 # Well, GPA Calcultor will need status router

  - name: OpenNCCU SCSR Helper
    url: https://help.opennccu.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /status # where "repo" is your repository name
  name: OpenNCCU Status
  cname: status.opennccu.com
  logoUrl: https://status.opennccu.com/logo.png
  favicon: https://status.opennccu.com/logo.png
  faviconSvg: https://status.opennccu.com/favicon.svg
  introTitle: OpenNCCU Service Status
  introMessage: Powered by Upptime. Contact us if you have any questions.
    <div class="icon-link-container">
    <a href="https://instagram.com/open.nccu" class="icon-link" target="_blank"><img
    src="https://status.opennccu.com/mdi-instagram.svg" class="icon-link" alt="Instagram"></a>
    <a href="mailto:opennccu@gmail.com" class="icon-link" target="_blank"><img
    src="https://status.opennccu.com/mdi-email.svg" alt="Mail"></a>
    <a href="https://discord.gg/epArwHVmpk" class="icon-link" target="_blank"><img
    src="https://status.opennccu.com/mdi-discord.svg" alt="Discord"></a>
    <div class="icon-divider"></div>
    <a href="https://forms.gle/yfooxi1BofpwCCDb9" target="_blank" class="icon-link">
    <img src="https://status.opennccu.com/mid-file-document.svg" alt="Form">
    <strong>Report Issue</strong>
    </a>
    <div class="icon-divider"></div>
    <a href="https://github.com/OpenNCCU/status" target="_blank" class="icon-link"><img
    src="https://status.opennccu.com/mdi-github.svg" alt="Github">
    <img class="icon-footnote" src="https://status.opennccu.com/favicon.svg" alt="Logo">
    </a>
    </div>

  # navbar:
  #   - title: GitHub
  #     href: https://github.com/OpenNCCU/status
  #   - title: Report Issue
  #     href: https://forms.gle/yfooxi1BofpwCCDb9

  themeUrl: https://status.opennccu.com/index.css
  customHeadHtml: <!-- HTML Meta Tags -->
    <meta name="description" content="Service Status of OpenNCCU">

    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="https://status.opennccu.com/">
    <meta property="og:type" content="website">
    <meta property="og:title" content="OpenNCCU Service Status">
    <meta property="og:description" content="Service Status of OpenNCCU">
    <meta property="og:image" content="https://status.opennccu.com/OG.png">

    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="status.opennccu.com">
    <meta property="twitter:url" content="https://status.opennccu.com/">
    <meta name="twitter:title" content="OpenNCCU Service Status">
    <meta name="twitter:description" content="Service Status of OpenNCCU">
    <meta name="twitter:image" content="https://status.opennccu.com/OG.png">

    <!-- Meta Tags Generated via https://www.opengraph.xyz -->

    <!-- Apple Web App -->
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="OpenNCCU Service Status">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <meta name="author" content="OpenNCCU">
    <link rel="author" href="https://opennccu.com/">
  customBodyHtml: "<!-- Custom HTML to add at the beginning of <body> -->"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
