# Change these first
owner: OpenNCCU # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: OpenNCCU App
    url: https://opennccu.com
  - name: OpenNCCU 選課系統
    url: https://course.opennccu.com
  - name: OpenNCCU SCSR API
    url: https://api-course.opennccu.com/
  - name: OpenNCCU Oauth
    url: https://oauth.opennccu.com/api/status
  - name: GPA Calculator
    url: https://gpa-calc.opennccu.com/api/gpa
    expectedStatusCodes:
      - 400 # Well GPA Calcultor will need status router
  - name: OpenNCCU Copy Checker 批量選課協助頁
    url: https://help.opennccu.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status # where "repo" is your repository name
  name: OpenNCCU Status
  introTitle: "OpenNCCU Status"
  introMessage: "OpenNCCU Status Page, powered by Uptime"
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/OpenNCCU/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
